-- TABLE Creation Queries

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(255)                            NOT NULL,
    password     VARCHAR(1200)                           NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE crops
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1200)                           NOT NULL
);

CREATE TABLE user_crops
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                 NOT NULL,
    crop_id     BIGINT                                 NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE              NOT NULL
);

CREATE TABLE alerts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                 NOT NULL,
    alert_type  VARCHAR(255)                           NOT NULL,
    priority    VARCHAR(255)                           NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE crop_alerts
(
    alert_id        BIGINT NOT NULL,
    user_crop_id    BIGINT NOT NULL,
    crop_alert_type VARCHAR(255) NOT NULL
);

CREATE TABLE task_alerts
(
    alert_id   BIGINT NOT NULL,
    task_type  VARCHAR(255) NOT NULL,
    due_time   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE weather_alerts
(
    alert_id       BIGINT NOT NULL,
    weather_type   VARCHAR(255) NOT NULL,
    forecasted_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- TABLE Constraint Queries

-- users table
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- crops table
ALTER TABLE crops
    ADD CONSTRAINT pk_crops PRIMARY KEY (id);

-- user_crops table
ALTER TABLE user_crops
    ADD CONSTRAINT pk_user_crops PRIMARY KEY (id);

ALTER TABLE user_crops
    ADD CONSTRAINT fk_user_crops_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_crops
    ADD CONSTRAINT fk_user_crops_crop FOREIGN KEY (crop_id) REFERENCES crops (id) ON DELETE CASCADE;

-- alerts table
ALTER TABLE alerts
    ADD CONSTRAINT pk_alerts PRIMARY KEY (id);

ALTER TABLE alerts
    ADD CONSTRAINT fk_alerts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- crop_alerts table

ALTER TABLE crop_alerts
    ADD CONSTRAINT pk_crop_alerts PRIMARY KEY (alert_id);

ALTER TABLE crop_alerts
    ADD CONSTRAINT fk_crop_alerts_alert FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE CASCADE;

ALTER TABLE crop_alerts
    ADD CONSTRAINT fk_crop_alerts_user_crop FOREIGN KEY (user_crop_id) REFERENCES user_crops (id) ON DELETE CASCADE;

-- task_alerts table

ALTER TABLE task_alerts
    ADD CONSTRAINT pk_task_alerts PRIMARY KEY (alert_id);

ALTER TABLE task_alerts
    ADD CONSTRAINT fk_task_alerts_alert FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE CASCADE;

-- weather_alerts table

ALTER TABLE weather_alerts
    ADD CONSTRAINT pk_weather_alerts PRIMARY KEY (alert_id);

ALTER TABLE weather_alerts
    ADD CONSTRAINT fk_weather_alerts_alert FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE CASCADE;