-- TABLE Creation Queries

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    full_name    VARCHAR(255)                            NOT NULL,
    password     VARCHAR(1200)                           NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE crops
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1200)                           NOT NULL
);

CREATE TABLE user_crops
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                 NOT NULL,
    crop_id     BIGINT                                 NOT NULL,
    selected_at TIMESTAMP WITH TIME ZONE              NOT NULL
);

-- TABLE Constraint Queries

-- users table
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- crops table
ALTER TABLE crops
    ADD CONSTRAINT pk_crops PRIMARY KEY (id);

-- user_crops table
ALTER TABLE user_crops
    ADD CONSTRAINT pk_user_crops PRIMARY KEY (id);

ALTER TABLE user_crops
    ADD CONSTRAINT fk_user_crops_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_crops
    ADD CONSTRAINT fk_user_crops_crop FOREIGN KEY (crop_id) REFERENCES crops (id) ON DELETE CASCADE;